Vus 103/test cache
ong-bitcoin-argentina/DIDI-SSI-Identity-issuer pull request #29
Opened 2022-02-09 19:24 UTC by DoloresGarciaE

- Se agregó supertest.

2022-02-09 19:31 UTC, fedelmar submitted a review, later dismissed

2022-02-09 20:59 UTC, MatiasOS requested changes
Solo un detalle de redacción.

2022-02-09 20:59 UTC, MatiasOS commented on .github/workflows/integrate.yml
> +      # Etiqueta usada para acceder al contenedor de servicio   redis:
Este línea quedó medio rara, no se entiende bien

2022-02-09 21:55 UTC, DoloresGarciaE commented on .github/workflows/integrate.yml
> +      # Etiqueta usada para acceder al contenedor de servicio   redis:
esta redactado asi en las github docs, pero ahora lo cambio

2022-02-11 14:03 UTC, MatiasOS approved these changes

2022-02-11 15:30 UTC, merged