Vus 129/add selfie
ong-bitcoin-argentina/DIDI-SSI-Identity-issuer pull request #31
Opened 2022-02-10 22:17 UTC by DoloresGarciaE

- se creo servicio para adherir la selfie

2022-02-11 14:10 UTC, MatiasOS requested changes
Hay problemas en la organización de código. Lo vemos por chat/llamada

2022-02-16 14:08 UTC, fedelmar commented on src/controllers/vus/createVerification.js
> +  const params = req.body;
Porque se decidió mover todo a una sola variable?

2022-02-16 18:44 UTC, fedelmar submitted a review, later dismissed

2022-02-16 21:09 UTC, MatiasOS approved these changes
:ship:

2022-02-16 21:47 UTC, merged