Vus 151/normalize error
ong-bitcoin-argentina/DIDI-SSI-Identity-issuer pull request #37
Opened 2022-02-23 17:34 UTC by DoloresGarciaE

- Se arregló la respuesta de error
- Se normalizaron los mensajes de error

2022-02-23 21:03 UTC, MatiasOS requested changes, later dismissed
Un pequeño detalle

2022-02-23 21:03 UTC, MatiasOS commented on src/services/vusService.js
> +  if (response.status === 400) throw response.json();
:medal_military:

2022-02-23 21:03 UTC, MatiasOS commented on src/services/vusService.js
> +    const result = vuSecurityPost(
Esto tiene que ir con **await**

2022-02-24 00:07 UTC, fedelmar approved these changes

2022-02-25 15:02 UTC, merged