Vus 141/add coverage test
ong-bitcoin-argentina/DIDI-SSI-Identity-issuer pull request #39
Opened 2022-02-24 16:08 UTC by DoloresGarciaE

- Se agregó reporte de coverage en los tests

2022-02-24 18:28 UTC, fedelmar submitted a review, later dismissed

2022-03-01 18:16 UTC, MatiasOS requested changes
Integrar con SonarCloud

2022-03-03 16:01 UTC, fedelmar approved these changes

2022-03-04 14:36 UTC, MatiasOS approved these changes

2022-03-04 16:44 UTC, merged