[VUS-192][VUS-193] Implementar emisión de credenciales
ong-bitcoin-argentina/DIDI-SSI-Identity-issuer pull request #54
Opened 2022-03-23 14:31 UTC by fedelmar

- Se implementa la emisión de credenciales en base al resultado de la validación de identidad

2022-03-26 20:54 UTC, MatiasOS requested changes
Una vez que se conoce el resultado de la validación, guardar en DB el resultado y los datos necesarios para emitr la credencial.

En un siguiente paso, crear un nuevo cron que verifique si hay tareas pendienes en DB, y las ejecute llamndo al emisor para emitir las credenciales. 

Hacerlo así en más fáci para testear y menos propenso a errores por asincronismos

2022-03-31 22:38 UTC, MatiasOS requested changes
Además de los detalles esos, crear 2 jobs separados para la emisión. Uno para cada credencial

2022-03-31 22:38 UTC, MatiasOS commented on src/constants/Constants.js
> +  PERSONAL_TEMP_ID: '62262ce12248912bdc580a36',
usar un nombre más descriptivo para PERSONAL_TEMP_ID y LOCATION_TEMP_ID.

2022-03-31 22:38 UTC, MatiasOS commented on src/jobs/credentialActions.js
> +} = require('../services/CredentialService');
createCredential y emmitCredential deberían respetar la interfaz como los otros servicios, Recibir como parametro un objeto con las key
Por ejmplo: 
```javascript
  const { data } = await createCredential({credentialData, did, templateId}});
  const credential = await emmitCredential({id})
```

2022-03-31 22:38 UTC, MatiasOS commented on src/jobs/credentialActions.js
> +  const { _id } = data[0];
Se puede evitar el uso de _id de alguna forma?

2022-04-04 15:45 UTC, DoloresGarciaE approved these changes

2022-04-04 17:11 UTC, MatiasOS approved these changes

2022-04-04 17:12 UTC, merged