update index
ong-bitcoin-argentina/DIDI-SSI-Identity-issuer pull request #63
Opened 2022-04-22 15:41 UTC by DoloresGarciaE

- Actualizacion servicio logger

2022-04-25 12:56 UTC, fedelmar submitted a review, later dismissed

2022-04-26 18:40 UTC, MatiasOS requested changes

2022-04-26 18:40 UTC, MatiasOS commented on .github/workflows/integrate.yml
> +          APP_INSIGTHS_IKEY: ${{ secrets.APP_INSIGTHS_IKEY }}
No es APP_INSIGTHS_IKEY, usar DISABLE_TELEMETRY_CLIENT

2022-04-26 20:41 UTC, MatiasOS approved these changes
:shipit:

2022-04-26 20:41 UTC, merged